from sqlalchemy import Column, String, Integer, Date, DateTime, DECIMAL, Text, JSON, Boolean
from config.database import Base
from datetime import datetime

class PlantGrowth(Base):
    __tablename__ = 'plant_growth'

    id = Column(Integer, primary_key=True, autoincrement=True, comment='主键ID')
    user_id = Column(Integer, comment='用户ID')
    plant_name = Column(String(100), comment='植物名称')
    plant_type = Column(String(50), comment='植物类型')
    variety = Column(String(100), comment='品种')
    plant_date = Column(Date, comment='种植日期')
    plant_location = Column(String(50), comment='种植地点')
    planting_method = Column(String(50), comment='种植方式')
    soil_type = Column(String(100), comment='土壤类型')
    pot_size = Column(String(50), comment='花盆尺寸')
    growth_stage = Column(String(20), comment='生长阶段')
    health_status = Column(String(20), comment='健康状态')
    height_cm = Column(DECIMAL(6, 2), comment='高度(cm)')
    leaf_count = Column(Integer, comment='叶片数量')
    flower_count = Column(Integer, comment='花朵数量')
    fruit_count = Column(Integer, comment='果实数量')
    ideal_temperature = Column(String(50), comment='理想温度')
    ideal_humidity = Column(String(50), comment='理想湿度')
    light_requirements = Column(String(100), comment='光照需求')
    watering_needs = Column(String(100), comment='浇水需求')
    fertilizing_needs = Column(String(100), comment='施肥需求')
    care_instructions = Column(Text, comment='养护说明')
    watering_guide = Column(Text, comment='浇水指南')
    fertilizing_guide = Column(Text, comment='施肥指南')
    pruning_guide = Column(Text, comment='修剪指南')
    repotting_guide = Column(Text, comment='换盆指南')
    propagation_methods = Column(Text, comment='繁殖方法')
    common_problems = Column(Text, comment='常见问题')
    pest_solutions = Column(Text, comment='病虫害防治')
    troubleshooting = Column(Text, comment='疑难解答')
    growth_notes = Column(Text, comment='生长记录')
    observations = Column(Text, comment='观察记录')
    challenges = Column(Text, comment='遇到的挑战')
    solutions = Column(Text, comment='解决方案')
    success_tips = Column(Text, comment='成功经验')
    germination_date = Column(Date, comment='发芽日期')
    flowering_date = Column(Date, comment='开花日期')
    fruiting_date = Column(Date, comment='结果日期')
    harvest_date = Column(Date, comment='收获日期')
    milestones = Column(JSON, comment='里程碑')
    last_watering = Column(Date, comment='上次浇水')
    last_fertilizing = Column(Date, comment='上次施肥')
    last_pruning = Column(Date, comment='上次修剪')
    next_care_date = Column(Date, comment='下次养护日期')
    cover_image = Column(String(500), comment='封面图片')
    growth_images = Column(JSON, comment='生长图片')
    tutorial_images = Column(JSON, comment='教程图片')
    care_videos = Column(JSON, comment='养护视频')
    purchase_price = Column(DECIMAL(8, 2), comment='购买价格')
    total_cost = Column(DECIMAL(8, 2), comment='总成本')
    harvest_amount = Column(DECIMAL(8, 2), comment='收获数量')
    harvest_unit = Column(String(20), comment='收获单位')
    is_active = Column(Integer, default=1, comment='是否活跃')
    watering_reminder = Column(Integer, default=0, comment='浇水提醒')
    fertilizing_reminder = Column(Integer, default=0, comment='施肥提醒')
    growth_reminder = Column(Integer, default=0, comment='生长记录提醒')
    days_grown = Column(Integer, comment='生长天数')
    growth_rate = Column(DECIMAL(6, 2), comment='生长速率')
    create_time = Column(DateTime, default=datetime.now, comment='创建时间')
    update_time = Column(DateTime, default=datetime.now, onupdate=datetime.now, comment='更新时间')
