from pydantic import BaseModel, Field, ConfigDict
from pydantic.alias_generators import to_camel
from datetime import date, datetime
from typing import Optional, Any, List, Dict
from module_admin.annotation.pydantic_annotation import as_query

@as_query
class DeviceQuery(BaseModel):
    model_config = ConfigDict(alias_generator=to_camel)

    device_name: Optional[str] = Field(default=None, description='设备名称')
    device_type: Optional[str] = Field(default=None, description='设备类型')
    device_status: Optional[str] = Field(default=None, description='设备状态')
    page_num: int = Field(default=1, description='当前页码')
    page_size: int = Field(default=10, description='每页数量')

class DeviceModel(BaseModel):
    model_config = ConfigDict(from_attributes=True, alias_generator=to_camel)

    id: Optional[int] = Field(default=None, description='主键ID')
    device_name: Optional[str] = Field(default=None, description='设备名称')
    device_type: Optional[str] = Field(default=None, description='设备类型')
    brand: Optional[str] = Field(default=None, description='品牌')
    model: Optional[str] = Field(default=None, description='型号')
    serial_number: Optional[str] = Field(default=None, description='序列号')
    color: Optional[str] = Field(default=None, description='颜色')
    device_status: Optional[str] = Field(default=None, description='设备状态')
    purchase_status: Optional[str] = Field(default=None, description='购买状态')
    storage_location: Optional[str] = Field(default=None, description='存放位置')
    location_type: Optional[str] = Field(default=None, description='位置类型')
    specific_spot: Optional[str] = Field(default=None, description='具体位置')
    quantity: Optional[int] = Field(default=None, description='数量')
    unit_price: Optional[float] = Field(default=None, description='单价')
    total_value: Optional[float] = Field(default=None, description='总价值')
    currency: Optional[str] = Field(default=None, description='货币')
    purchase_date: Optional[date] = Field(default=None, description='购买日期')
    purchase_from: Optional[str] = Field(default=None, description='购买渠道')
    warranty_period: Optional[int] = Field(default=None, description='保修期(月)')
    warranty_end_date: Optional[date] = Field(default=None, description='保修截止日期')
    invoice_number: Optional[str] = Field(default=None, description='发票号码')
    start_use_date: Optional[date] = Field(default=None, description='启用日期')
    estimated_lifespan: Optional[int] = Field(default=None, description='预计寿命(月)')
    usage_frequency: Optional[str] = Field(default=None, description='使用频率')
    last_used_date: Optional[date] = Field(default=None, description='最后使用日期')
    specifications: Optional[Any] = Field(default=None, description='规格参数')
    accessories: Optional[Any] = Field(default=None, description='配件列表')
    maintenance_records: Optional[Any] = Field(default=None, description='维护记录')
    repair_history: Optional[Any] = Field(default=None, description='维修历史')
    next_maintenance_date: Optional[date] = Field(default=None, description='下次维护日期')
    device_images: Optional[Any] = Field(default=None, description='设备图片')
    manual_path: Optional[str] = Field(default=None, description='说明书路径')
    warranty_card_image: Optional[str] = Field(default=None, description='保修卡图片')
    invoice_image: Optional[str] = Field(default=None, description='发票图片')
    tags: Optional[Any] = Field(default=None, description='标签')
    notes: Optional[str] = Field(default=None, description='备注')
    important_level: Optional[str] = Field(default=None, description='重要程度')
    is_shared: Optional[bool] = Field(default=None, description='是否共享')
    shared_with: Optional[Any] = Field(default=None, description='共享给谁')
    low_battery_reminder: Optional[bool] = Field(default=None, description='低电量提醒')
    warranty_expire_reminder: Optional[bool] = Field(default=None, description='保修过期提醒')
    is_active: Optional[bool] = Field(default=None, description='是否有效')
    create_time: Optional[datetime] = Field(default=None, description='创建时间')

class DeviceCreate(BaseModel):
    model_config = ConfigDict(alias_generator=to_camel)

    device_name: str = Field(..., description='设备名称')
    device_type: str = Field(..., description='设备类型')
    brand: str = Field(..., description='品牌')
    model: str = Field(..., description='型号')
    serial_number: Optional[str] = Field(default=None, description='序列号')
    color: Optional[str] = Field(default=None, description='颜色')
    device_status: Optional[str] = Field(default='已使用', description='设备状态')
    purchase_status: Optional[str] = Field(default='已拥有', description='购买状态')
    storage_location: str = Field(..., description='存放位置')
    location_type: str = Field(..., description='位置类型')
    specific_spot: Optional[str] = Field(default=None, description='具体位置')
    quantity: int = Field(default=1, description='数量')
    unit_price: Optional[float] = Field(default=None, description='单价')
    total_value: Optional[float] = Field(default=None, description='总价值')
    currency: Optional[str] = Field(default='CNY', description='货币')
    purchase_date: Optional[date] = Field(default=None, description='购买日期')
    purchase_from: Optional[str] = Field(default=None, description='购买渠道')
    warranty_period: Optional[int] = Field(default=None, description='保修期(月)')
    warranty_end_date: Optional[date] = Field(default=None, description='保修截止日期')
    invoice_number: Optional[str] = Field(default=None, description='发票号码')
    start_use_date: Optional[date] = Field(default=None, description='启用日期')
    estimated_lifespan: Optional[int] = Field(default=None, description='预计寿命(月)')
    usage_frequency: Optional[str] = Field(default=None, description='使用频率')
    last_used_date: Optional[date] = Field(default=None, description='最后使用日期')
    device_images: Optional[Any] = Field(default=None, description='设备图片')
    manual_path: Optional[str] = Field(default=None, description='说明书路径')
    warranty_card_image: Optional[str] = Field(default=None, description='保修卡图片')
    invoice_image: Optional[str] = Field(default=None, description='发票图片')
    notes: Optional[str] = Field(default=None, description='备注')
    important_level: Optional[str] = Field(default='一般', description='重要程度')
    specifications: Optional[Any] = Field(default=None, description='规格参数')
    accessories: Optional[Any] = Field(default=None, description='配件列表')
    software_info: Optional[str] = Field(default=None, description='软件信息')
    maintenance_records: Optional[Any] = Field(default=None, description='维护记录')
    repair_history: Optional[Any] = Field(default=None, description='维修历史')
    next_maintenance_date: Optional[date] = Field(default=None, description='下次维护日期')
    tags: Optional[Any] = Field(default=None, description='标签')
    is_shared: Optional[bool] = Field(default=False, description='是否共享')
    shared_with: Optional[Any] = Field(default=None, description='共享给谁')
    low_battery_reminder: Optional[bool] = Field(default=False, description='低电量提醒')
    warranty_expire_reminder: Optional[bool] = Field(default=False, description='保修过期提醒')

class DeviceUpdate(DeviceCreate):
    id: int = Field(..., description='主键ID')
