from pydantic import BaseModel, ConfigDict, Field
from pydantic.alias_generators import to_camel
from typing import Optional, List, Union, Dict
from datetime import date, datetime
from module_admin.annotation.pydantic_annotation import as_query

class PlantBase(BaseModel):
    plant_name: str = Field(description='植物名称')
    plant_type: Optional[str] = Field(None, description='植物类型')
    variety: Optional[str] = Field(None, description='品种')
    plant_date: Optional[date] = Field(None, description='种植日期')
    plant_location: Optional[str] = Field(None, description='种植地点')
    planting_method: Optional[str] = Field(None, description='种植方式')
    soil_type: Optional[str] = Field(None, description='土壤类型')
    pot_size: Optional[str] = Field(None, description='花盆尺寸')
    growth_stage: Optional[str] = Field(None, description='生长阶段')
    health_status: Optional[str] = Field(None, description='健康状态')
    height_cm: Optional[float] = Field(None, description='高度(cm)')
    leaf_count: Optional[int] = Field(None, description='叶片数量')
    flower_count: Optional[int] = Field(None, description='花朵数量')
    fruit_count: Optional[int] = Field(None, description='果实数量')
    ideal_temperature: Optional[str] = Field(None, description='理想温度')
    ideal_humidity: Optional[str] = Field(None, description='理想湿度')
    light_requirements: Optional[str] = Field(None, description='光照需求')
    watering_needs: Optional[str] = Field(None, description='浇水需求')
    fertilizing_needs: Optional[str] = Field(None, description='施肥需求')
    care_instructions: Optional[str] = Field(None, description='养护说明')
    watering_guide: Optional[str] = Field(None, description='浇水指南')
    fertilizing_guide: Optional[str] = Field(None, description='施肥指南')
    pruning_guide: Optional[str] = Field(None, description='修剪指南')
    repotting_guide: Optional[str] = Field(None, description='换盆指南')
    propagation_methods: Optional[str] = Field(None, description='繁殖方法')
    common_problems: Optional[str] = Field(None, description='常见问题')
    pest_solutions: Optional[str] = Field(None, description='病虫害防治')
    troubleshooting: Optional[str] = Field(None, description='疑难解答')
    growth_notes: Optional[str] = Field(None, description='生长记录')
    observations: Optional[str] = Field(None, description='观察记录')
    challenges: Optional[str] = Field(None, description='遇到的挑战')
    solutions: Optional[str] = Field(None, description='解决方案')
    success_tips: Optional[str] = Field(None, description='成功经验')
    germination_date: Optional[date] = Field(None, description='发芽日期')
    flowering_date: Optional[date] = Field(None, description='开花日期')
    fruiting_date: Optional[date] = Field(None, description='结果日期')
    harvest_date: Optional[date] = Field(None, description='收获日期')
    milestones: Optional[Union[List, Dict, str]] = Field(None, description='里程碑')
    last_watering: Optional[date] = Field(None, description='上次浇水')
    last_fertilizing: Optional[date] = Field(None, description='上次施肥')
    last_pruning: Optional[date] = Field(None, description='上次修剪')
    next_care_date: Optional[date] = Field(None, description='下次养护日期')
    cover_image: Optional[str] = Field(None, description='封面图片')
    growth_images: Optional[Union[List[str], str]] = Field(None, description='生长图片')
    tutorial_images: Optional[Union[List[str], str]] = Field(None, description='教程图片')
    care_videos: Optional[Union[List[str], str]] = Field(None, description='养护视频')
    purchase_price: Optional[float] = Field(None, description='购买价格')
    total_cost: Optional[float] = Field(None, description='总成本')
    harvest_amount: Optional[float] = Field(None, description='收获数量')
    harvest_unit: Optional[str] = Field(None, description='收获单位')
    is_active: Optional[int] = Field(1, description='是否活跃')
    watering_reminder: Optional[int] = Field(0, description='浇水提醒')
    fertilizing_reminder: Optional[int] = Field(0, description='施肥提醒')
    growth_reminder: Optional[int] = Field(0, description='生长记录提醒')
    days_grown: Optional[int] = Field(None, description='生长天数')
    growth_rate: Optional[float] = Field(None, description='生长速率')

class PlantModel(PlantBase):
    id: Optional[int] = Field(None, description='主键ID')
    user_id: Optional[int] = Field(None, description='用户ID')
    create_time: Optional[datetime] = Field(None, description='创建时间')
    update_time: Optional[datetime] = Field(None, description='更新时间')

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)

class PlantQuery(BaseModel):
    page_num: int = Field(1, description='当前页码')
    page_size: int = Field(10, description='每页条数')
    plant_name: Optional[str] = Field(None, description='植物名称')
    plant_type: Optional[str] = Field(None, description='植物类型')
    growth_stage: Optional[str] = Field(None, description='生长阶段')
    health_status: Optional[str] = Field(None, description='健康状态')
    begin_time: Optional[str] = Field(None, description='开始时间')
    end_time: Optional[str] = Field(None, description='结束时间')
